#version 460

#include "SMAA.h"

layout(binding = 6) uniform SMAATexture2D(resolved_image);
layout(binding = 7) uniform SMAATexture2D(blend_texture);

layout(binding = 8) uniform writeonly image2D smaa_image;

void main(void)
{
  ivec2 coord = ivec2(gl_GlobalInvocationID.xy);

  if (coord.x < pc.smaa_rt_metrics.z && coord.y < pc.smaa_rt_metrics.w)  
  {
    vec4 color = SMAANeighborhoodBlendingCS(coord, resolved_image, blend_texture);
    imageStore(smaa_image, coord, color);
  }
}
